name: build

on: [pull_request, push, workflow_dispatch]

jobs:
  build:
    strategy:
      matrix:
        java: [17]
        os: [ubuntu-22.04, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v3

      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'adopt'

      - name: Make Gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Build with LWJGL 3.3.2
        run: ./gradlew buildLwjgl32

      - name: Build with LWJGL 3.3.3
        run: ./gradlew buildLwjgl33

      - name: Capture build artifacts for LWJGL 3.3.2
        uses: actions/upload-artifact@v4
        with:
          name: lwjgl-3.3.2-artifacts
          path: build/libs/*-lwjgl-3.3.2.jar

      - name: Capture build artifacts for LWJGL 3.3.3
        uses: actions/upload-artifact@v4
        with:
          name: lwjgl-3.3.3-artifacts
          path: build/libs/*-lwjgl-3.3.3.jar
